### ISSUE TITLE
Don't repeat yourself (DRY)

### ISSUE THREAD

**Issue by kosterm14** [moonlightlizaa/server-side-rendering#8]
Zet herhalende code in dezelfde h2

``` css
h2 {
  font: var(--vtH2Font);
  color: var(--vtDarkBlue);
}
```
``` css
h2 {
    font-family: var(--vtPrimaryFont);
    font-size: 24px;
    color: var(--vtDarkBlue);
  }
```
